version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.51.2
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - source: alert.rules.yml
        target: /etc/prometheus/alert.rules.yml
    networks:
      - healthify_net
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:10.4.2
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - healthify_net
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  node-exporter:
    image: prom/node-exporter:v1.7.0
    networks:
      - healthify_net
    ports:
      - "9100:9100"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/healthify?sslmode=disable"
    networks:
      - healthify_net
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  grafana_data:

networks:
  healthify_net:
    external: true

configs:
  prometheus.yml:
    external: true
  alert.rules.yml:
    external: true
